version: 0.2

env:
  variables:
    S3_BUCKET: "jerrysmasks.com"

phases:
  install:
    commands:
      - echo `npm -v`
      - echo NODE_ENV=$NODE_ENV
      - npm install 
      - npm install --only=dev
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Build CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION
      - echo Build CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - node_modules/.bin/gridsome build
  post_build:
    commands:
      - aws s3 cp --recursive $CODEBUILD_SRC_DIR/dist/ s3://$S3_BUCKET/ --acl public-read --recursive --cache-control 'max-age=31104000'