version: 0.2

environment_variables:
  plaintext:
    S3_BUCKET: "jerrysmasks.com"
    CLOUDFRONT_DISTRIBUTION_ID: "E7C381K3UGYB0"
    FRONTEND_ENV: "prod"

phases:
  install:
    commands:
      - echo `npm -v`
      - echo NODE_ENV=$NODE_ENV
      - npm install 
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Build CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION
      - echo Build CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - echo Build CODEBUILD_BUILD_NUMBER $CODEBUILD_BUILD_NUMBER
      - echo Build CODEBUILD_START_TIME $CODEBUILD_START_TIME
      - npm run build
      - cp $CODEBUILD_SRC_DIR/env/env.$FRONTEND_ENV.js $CODEBUILD_SRC_DIR/public/js/env.js
      - sed -i "s/{VERSION}/$CODEBUILD_START_TIME/g" ./public/*.html
      - sed -i "s/{VERSION}/$CODEBUILD_START_TIME/g" ./public/order/*.html
      - sed -i "s/{VERSION}/$CODEBUILD_START_TIME/g" ./public/donate/*.html
  post_build:
    commands:
      - aws s3 cp $CODEBUILD_SRC_DIR/public/js/ s3://$S3_BUCKET/js/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/public/css/ s3://$S3_BUCKET/css/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/public/img/ s3://$S3_BUCKET/img/ --acl public-read --recursive --cache-control 'max-age=31104000'
      - aws s3 cp $CODEBUILD_SRC_DIR/public/order/ s3://$S3_BUCKET/order/ --acl public-read --recursive --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws s3 cp $CODEBUILD_SRC_DIR/public/donate/ s3://$S3_BUCKET/donate/ --acl public-read --recursive --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws s3 cp $CODEBUILD_SRC_DIR/public/index.html s3://$S3_BUCKET/index.html --acl public-read --recursive --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" 